/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BendaharaRouteImport } from './routes/bendahara'
import { Route as KasRouteImport } from './routes/kas'
import { Route as LogRouteImport } from './routes/log'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as KasBayarRouteImport } from './routes/kas/bayar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BendaharaRoute = BendaharaRouteImport.update({
  id: '/bendahara',
  path: '/bendahara',
  getParentRoute: () => rootRouteImport,
} as any)
const KasRoute = KasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KasBayarRoute = KasBayarRouteImport.update({
  id: '/bayar',
  path: '/bayar',
  getParentRoute: () => KasRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bendahara': typeof BendaharaRoute
  '/kas': typeof KasRouteWithChildren
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/kas/bayar': typeof KasBayarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bendahara': typeof BendaharaRoute
  '/kas': typeof KasRouteWithChildren
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/kas/bayar': typeof KasBayarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bendahara': typeof BendaharaRoute
  '/kas': typeof KasRouteWithChildren
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/kas/bayar': typeof KasBayarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bendahara'
    | '/kas'
    | '/log'
    | '/login'
    | '/api/$'
    | '/kas/bayar'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bendahara'
    | '/kas'
    | '/log'
    | '/login'
    | '/api/$'
    | '/kas/bayar'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bendahara'
    | '/kas'
    | '/log'
    | '/login'
    | '/api/$'
    | '/kas/bayar'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BendaharaRoute: typeof BendaharaRoute
  KasRoute: typeof KasRouteWithChildren
  LogRoute: typeof LogRoute
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bendahara': {
      id: '/bendahara'
      path: '/bendahara'
      fullPath: '/bendahara'
      preLoaderRoute: typeof BendaharaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kas': {
      id: '/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof KasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kas/bayar': {
      id: '/kas/bayar'
      path: '/bayar'
      fullPath: '/kas/bayar'
      preLoaderRoute: typeof KasBayarRouteImport
      parentRoute: typeof KasRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KasRouteChildren {
  KasBayarRoute: typeof KasBayarRoute
}

const KasRouteChildren: KasRouteChildren = {
  KasBayarRoute: KasBayarRoute,
}

const KasRouteWithChildren = KasRoute._addFileChildren(KasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BendaharaRoute: BendaharaRoute,
  KasRoute: KasRouteWithChildren,
  LogRoute: LogRoute,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
